import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useState, useEffect } from 'react';
import LanguageSelector from '@/components/LanguageSelector';
import { FormattedMessage } from 'react-intl';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
	const serverData = JSON.parse(data);

	const [time, setTime] = useState();

	useEffect(() => {
		fetch('/api/time')
			.then((res) => res.json())
			.then((json) => setTime(new Date(json.time)));
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div className={styles.description}>
					<div>
						<FormattedMessage id='home.builtByMessage' />
					</div>
				</div>
				<LanguageSelector />

				<div className={styles.center}>
					<Image
						className={styles.logo}
						src='/next.svg'
						alt='Next.js Logo'
						width={180}
						height={37}
						priority
					/>
				</div>
				<div className={styles.center}>
					<h1>
						<FormattedMessage id='home.welcomeMessage' /> <br />{' '}
						{time &&
							`The time is ${time.getHours()}:${time.getMinutes()}:${time.getSeconds()}`}
					</h1>
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps() {
	const data = JSON.stringify({ time: new Date() });
	return { props: { data } };
}
