import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }) {
	const serverData = JSON.parse(data);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div className={styles.description}>
					<div>Built By Gayashan</div>
				</div>

				<div className={styles.center}>
					<Image
						className={styles.logo}
						src='/next.svg'
						alt='Next.js Logo'
						width={180}
						height={37}
						priority
					/>
				</div>
				<div className={styles.center}>
					<h1>
						Welcome to Next.js! <br /> The time is {serverData.time}
					</h1>
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps() {
	const data = JSON.stringify({ time: new Date() });
	return { props: { data } };
}
